# This configuration file should contain all required configuration parameters
# for the OPEN ingest workflow to run to completion.
lineages:
  - h1n1pdm
  - h3n2
  - vic

segments:
  - pb2
  - pb1
  - pa
  - ha
  - np
  - na
  - mp
  - ns

genspectrum_metadata_fields:
  - accession
  - accessionVersion
  - specimenCollectorSampleId
  - sampleCollectionDate
  - hostNameScientific
  - ncbiReleaseDate
  - country
  - division
  - authors
  - authorAffiliations
  - insdcAccessionBase_seg1
  - insdcAccessionBase_seg2
  - insdcAccessionBase_seg3
  - insdcAccessionBase_seg4
  - insdcAccessionBase_seg5
  - insdcAccessionBase_seg6
  - insdcAccessionBase_seg7
  - insdcAccessionBase_seg8

# Filter by fields available in GenSpecturm LAPIS
genspectrum_filters:
  hostNameScientific: "Homo sapiens"

genspectrum_fastaHeaderTemplate: "{accession}_{.segment}"  # e.g. GS_00BCP0A_seg4

curate:
  field_map:
    accession: accession
    accessionVersion: accession_version
    specimenCollectorSampleId: strain
    sampleCollectionDate: date
    hostNameScientific: host
    ncbiReleaseDate: date_released
    country: country
    division: division
    authors: full_authors
    authorAffiliations: institution

  # TODO: add stricter regex
  strain_regex: '^(A|B)/.+/.+$'
  # Back up strain name field to use if 'strain' doesn't match regex above
  strain_backup_fields: ['accession']

  date_fields:
    - date
    - date_released
  expected_date_formats:
    - "%Y"
    - "%Y-%m"
    - "%Y-%m-%d"

  genspectrum_division_field: division
  location_field: location

  titlecase:
    # List of string fields to titlecase
    fields: ["region", "country", "division", "location"]
    # List of abbreviations not cast to titlecase, keeps uppercase
    abbreviations: ["USA"]
    # Articles that should not be cast to titlecase
    articles: [
      "and", "d", "de", "del", "des", "di", "do", "en", "l", "la", "las", "le",
      "los", "nad", "of", "op", "sur", "the", "y" ]

  # Metadata field that contains the list of authors associated with the sequence
  authors_field: "full_authors"
  # Default value to use if the authors field is empty
  authors_default_value: "?"
  # Name to use for the generated abbreviated authors field
  abbr_authors_field: "authors"

  local_geolocation_rules: ../../ingest/defaults/geolocation_rules.tsv

  annotations: annotations.tsv
  annotations_id: strain

  record_id_field: accession
  strain_field: strain

  metadata_columns:
    - accession
    - accession_version
    - strain
    - date
    - date_released
    - region
    - country
    - division
    - location
    - host
    - authors
    - full_authors
    - institution

nextclade:
  nextclade:
  h3n2:
    ha:
      dataset_name: nextstrain/flu/h3n2/ha
      # Add derived haplotypes to the Nextclade annotations
      # Uses the original columns from the Nextclade TSV
      derived_haplotypes:
        genes:
          - HA1
        clade_column: clade
        mutations_column: "founderMuts['clade'].aaSubstitutions"
        derived_haplotype_column: subclade_haplotype_ha
      # Add predefined haplotypes to the Nextclade annotations
      # Uses the original columns from the Nextclade TSV
      emerging_haplotypes:
        haplotypes: ../../config/h3n2/ha/emerging_haplotypes.tsv
        clade_column: clade
        emerging_haplotype_column: emerging_haplotype_ha
      # Field used to merge with the metdata.
      id_field: seqName
      # Used to rename fields and only listed fields will be merged with the
      # metadata in final output. Must include the id_field defined above.
      # The derived_haplotype_column and emerging_haplotype_column are automatically
      # added if not defined in the field map.
      field_map:
        seqName: seqName
        clade: subclade_nextclade_ha
        qc.overallStatus: qc.overallStatus_ha
    na:
      dataset_name: nextstrain/flu/h3n2/na
      id_field: seqName
      field_map:
        seqName: seqName
        clade: subclade_nextclade_na
        qc.overallStatus: qc.overallStatus_na
    pb2:
      dataset_name: nextstrain/flu/h3n2/pb2
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_pb2
    pb1:
      dataset_name: nextstrain/flu/h3n2/pb1
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_pb1
    pa:
      dataset_name: nextstrain/flu/h3n2/pa
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_pa
    np:
      dataset_name: nextstrain/flu/h3n2/np
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_np
    mp:
      dataset_name: nextstrain/flu/h3n2/mp
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_mp
    ns:
      dataset_name: nextstrain/flu/h3n2/ns
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_ns
  h1n1pdm:
    ha:
      dataset_name: nextstrain/flu/h1n1pdm/ha
      derived_haplotypes:
        genes:
          - HA1
        clade_column: clade
        mutations_column: "founderMuts['clade'].aaSubstitutions"
        derived_haplotype_column: subclade_haplotype_ha
      emerging_haplotypes:
        haplotypes: ../../config/h1n1pdm/ha/emerging_haplotypes.tsv
        clade_column: clade
        emerging_haplotype_column: emerging_haplotype_ha
      id_field: seqName
      field_map:
        seqName: seqName
        clade: subclade_nextclade_ha
        qc.overallStatus: qc.overallStatus_ha
    na:
      dataset_name: nextstrain/flu/h1n1pdm/na
      id_field: seqName
      field_map:
        seqName: seqName
        clade: subclade_nextclade_na
        qc.overallStatus: qc.overallStatus_na
    pb2:
      dataset_name: nextstrain/flu/h1n1pdm/pb2
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_pb2
    pb1:
      dataset_name: nextstrain/flu/h1n1pdm/pb1
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_pb1
    pa:
      dataset_name: nextstrain/flu/h1n1pdm/pa
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_pa
    np:
      dataset_name: nextstrain/flu/h1n1pdm/np
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_np
    mp:
      dataset_name: nextstrain/flu/h1n1pdm/mp
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_mp
    ns:
      dataset_name: nextstrain/flu/h1n1pdm/ns
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_ns
  vic:
    ha:
      dataset_name: nextstrain/flu/vic/ha
      derived_haplotypes:
        genes:
          - HA1
        clade_column: clade
        mutations_column: "founderMuts['clade'].aaSubstitutions"
        derived_haplotype_column: subclade_haplotype_ha
      emerging_haplotypes:
        haplotypes: ../../config/vic/ha/emerging_haplotypes.tsv
        clade_column: clade
        emerging_haplotype_column: emerging_haplotype_ha
      id_field: seqName
      field_map:
        seqName: seqName
        clade: subclade_nextclade_ha
        qc.overallStatus: qc.overallStatus_ha
    na:
      dataset_name: nextstrain/flu/vic/na
      id_field: seqName
      field_map:
        seqName: seqName
        clade: subclade_nextclade_na
        qc.overallStatus: qc.overallStatus_na
    pb2:
      dataset_name: nextstrain/flu/vic/pb2
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_pb2
    pb1:
      dataset_name: nextstrain/flu/vic/pb1
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_pb1
    pa:
      dataset_name: nextstrain/flu/vic/pa
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_pa
    np:
      dataset_name: nextstrain/flu/vic/np
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_np
    mp:
      dataset_name: nextstrain/flu/vic/mp
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_mp
    ns:
      dataset_name: nextstrain/flu/vic/ns
      id_field: seqName
      field_map:
        seqName: seqName
        qc.overallStatus: qc.overallStatus_ns
