"""
This is the main ingest Snakefile that orchestrates the full ingest workflow
and defines its default outputs.
"""
# The workflow filepaths are written relative to this Snakefile's base directory
workdir: workflow.current_basedir

# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "defaults/config.yaml"

wildcard_constraints:
    # Expected lineages that should match the standardized output lineages
    # in scripts/standardized-lineage
    lineage = r'h1n1pdm|h3n2|vic|yam',
    segment = r'pb2|pb1|pa|ha|np|na|mp|ns',


rule all:
    input:
        metadata = expand("results/{lineage}/metadata.tsv", lineage=config["lineages"]),
        sequences = expand("results/{lineage}/{segment}/sequences.fasta", lineage=config["lineages"], segment=config["segments"]),


include: "rules/prepare_ndjson.smk"
include: "rules/curate.smk"


if "custom_rules" in config:
    for rule_file in config["custom_rules"]:

        include: rule_file
