#!/usr/bin/env python3
"""
Filter NDJSON by matching records by lineage and host
"""
import argparse
from sys import stdin, exit
from typing import Iterable, List
from augur.io.json import dump_ndjson, load_ndjson
from augur.io.print import print_err


def filter_records(records: Iterable[dict],
                   record_id_field: str,
                   lineage_field: str,
                   host_field: str|None,
                   lineages_to_include: List[str],
                   hosts_to_include: List[str]) -> Iterable:
    """
    Filter for *records* that have *lineage_field* and *host_field* matching
    the *lineages_to_include* and *host_to_include*.

    Records that do not match will be skipped.
    """
    for record in records:
        record_id = record.get(record_id_field, "")
        lineage = record.get(lineage_field)

        if lineage is None:
            raise Exception(f"Records must have the expected lineage field: {lineage_field!r}")

        if host_field:
            host = record.get(host_field)
            if host is None:
                raise Exception(f"Records must have the expected host field: {host_field!r}")
        else:
            host = "N/A"

        if lineage in lineages_to_include and (host=="N/A" or host in hosts_to_include):
            yield record
        else:
            print_err(f"WARNING: Skipping record {record_id!r} because it does not match filters")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument("--id-field", default="gisaid_epi_isl",
        help="The record field containing the record id.")
    parser.add_argument("--lineage-field", required=True,
        help="The record field containing the standardized lineage.")
    parser.add_argument("--lineages", nargs="+", required=True,
        help="Lineages to include in the output.")
    parser.add_argument("--host-field", default=None,
        help="The record field containing the host (optional)")
    parser.add_argument("--hosts", nargs="+",
        help="Hosts to include in the output directory (optional)")

    args = parser.parse_args()

    if args.host_field and not args.hosts:
        print_err("Host field provided without providing hosts to query on")
        exit(2)

    records = load_ndjson(stdin)
    modified_records = filter_records(
        records,
        args.id_field,
        args.lineage_field,
        args.host_field,
        args.lineages,
        args.hosts)
    dump_ndjson(modified_records)
