#!/usr/bin/env python3
"""
Filter NDJSON by field value.
"""
import argparse
from csv import DictReader
from sys import stdin
from typing import Iterable
from augur.io.json import dump_ndjson, load_ndjson
from augur.io.print import print_err
from augur.utils import read_entries


def filter_by_value(records: Iterable[dict],
                    field: str,
                    include_values: set[str]) -> Iterable[dict]:
    """
    Filter *records* for record that has *field* value that are
    included in the *include_values*.
    """
    for record in records:
        assert field in record, f"Records must include field {field!r}"

        if record[field] in include_values:
            yield record


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument("--field", required=True,
        help="The record field for filtering.")
    parser.add_argument("--include", required=True,
        help="A text file with values to include, with one value per line.")

    args = parser.parse_args()

    include_values = set(read_entries(args.include))
    records = load_ndjson(stdin)
    filtered_records = filter_by_value(records, args.field, include_values)
    dump_ndjson(filtered_records)
