#!/usr/bin/env python3
"""
Determine which record to prioritize for duplicate strain names.
Outputs a text file with a single record id per line.
"""
import argparse
from collections import defaultdict
from csv import DictReader
from enum import Enum
from functools import cmp_to_key
from sys import stdin
from typing import Iterable
from augur.io.json import as_json, load_ndjson
from augur.io.print import print_err


class PriorityReason(Enum):
    """
    Priority reasons:
    - Strain id is included in the TSV providied via `--prioritized-ids`
    - First record of strain
    """
    HARDCODED = "hardcoded"
    HAS_HA = "has HA"
    HAS_NA = "has NA"
    FIRST_RECORD = "first record"


class StrainRecord:
    """
    A single record for a strain.
    """

    def __init__(self, id):
        self.id: str = id
        self.reasons: set[PriorityReason] = set()

    def to_dict(self):
        return {"id": self.id, "reasons": sorted(x.value for x in self.reasons)}


def load_prioritized_ids(prioritized_ids_file: str) -> dict:
    """
    Parse *prioritized_ids_file* to return a dict with the
    `strain` as the key and `id` as the value.

    Raises an Exception if there are duplicate strains in the file.
    """
    prioritized_ids = {}
    with open(prioritized_ids_file, "r", newline="") as fh:
        reader = DictReader(fh, delimiter="\t")
        for row in reader:
            strain = row["strain"]
            record_id = row["id"]

            if strain in prioritized_ids:
                raise Exception(f"Found duplicate strain {strain!r} in {prioritized_ids_file!r}.")

            prioritized_ids[strain] = record_id

    return prioritized_ids


def track_ids_per_strain(records: Iterable[dict],
                         strain_field: str,
                         id_field: str,
                         seq_field: str,
                         hardcoded_ids: dict) -> dict[str, list[StrainRecord]]:
    """
    Iterate over *records* to make list of StrainRecords per strain.
    """
    ids_per_strain = defaultdict(list)

    for record in records:
        strain = record.get(strain_field)
        record_id = record.get(id_field)
        sequences = record.get(seq_field)

        if strain is None:
            raise Exception(f"Records must have the expected strain field {strain_field!r}")

        if record_id is None:
            raise Exception(f"Records must have the expected id field {id_field!r}")

        if sequences is None:
            raise Exception(f"Records must have the expected sequences field {seq_field!r}")

        strain_record = StrainRecord(record_id)

        if strain not in ids_per_strain:
            strain_record.reasons.add(PriorityReason.FIRST_RECORD)

        if hardcoded_id := hardcoded_ids.get(strain):
            if hardcoded_id == record_id:
                strain_record.reasons.add(PriorityReason.HARDCODED)

        if len(sequences.get("ha", [])) > 0:
            strain_record.reasons.add(PriorityReason.HAS_HA)

        if len(sequences.get("na", [])) > 0:
            strain_record.reasons.add(PriorityReason.HAS_NA)

        ids_per_strain[strain].append(strain_record)

    return ids_per_strain


def compare_priority(record1: StrainRecord, record2: StrainRecord):
    """
    Compare *record1* and *record2* to determine which record to prioritize.
    """
    assert not (
        PriorityReason.HARDCODED in record1.reasons and
        PriorityReason.HARDCODED in record2.reasons), \
        f"""
        Only one record should be {PriorityReason.HARDCODED.value!r}:
            {record1!r}
            {record2!r}
        """

    assert not (
        PriorityReason.FIRST_RECORD in record1.reasons and
        PriorityReason.FIRST_RECORD in record2.reasons), \
        f"""
        Only one record should be {PriorityReason.FIRST_RECORD.value!r}:
            {record1!r}
            {record2!r}
        """

    # Prioritize the hardcoded id
    if PriorityReason.HARDCODED in record1.reasons:
        return -1
    if PriorityReason.HARDCODED in record2.reasons:
        return 1

    # Prioritize the record that has HA segment only if the other record
    # does not have HA
    if (PriorityReason.HAS_HA in record1.reasons and
        PriorityReason.HAS_HA not in record2.reasons):
        return -1
    if (PriorityReason.HAS_HA in record2.reasons and
        PriorityReason.HAS_HA not in record1.reasons):
        return 1

    # Prioritize the record that has NA segment only if the other record
    # does not have NA
    if (PriorityReason.HAS_NA in record1.reasons and
        PriorityReason.HAS_NA not in record2.reasons):
        return -1
    if (PriorityReason.HAS_NA in record2.reasons and
        PriorityReason.HAS_NA not in record1.reasons):
        return 1

    # Prioritize the first record in the NDJSON
    if PriorityReason.FIRST_RECORD in record1.reasons:
        return -1
    if PriorityReason.FIRST_RECORD in record2.reasons:
        return 1

    # Otherwise records are considered equal
    return 0


def pick_id_per_strain(ids_per_strain: dict[str, list[StrainRecord]]) -> list:
    """
    For each strain in *ids_per_strain*, pick a single id to include in
    the output.
    """
    ids_to_output = []

    for strain, records in ids_per_strain.items():
        records.sort(key=cmp_to_key(compare_priority))

        # Logging sorted records for debugging purposes
        print_err(as_json({"strain": strain, "records": [x.to_dict() for x in records]}))

        ids_to_output.append(records[0].id)

    return ids_to_output


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument("--strain-field", default="strain",
        help="The record field containing the strain name.")
    parser.add_argument("--id-field", default="gisaid_epi_isl",
        help="The record field containing a record id. " + \
             "If providing the `--prioritized-ids` file, then this id field " + \
             "will be used to match the prioritized ids. " + \
             "Also included in the warning logs for records with duplicate strains.")
    parser.add_argument("--seq-field", default="sequences",
        help="The record field containing the sequences." + \
             "Allows the script to prioritize the records with HA and NA segments." )
    parser.add_argument("--prioritized-ids",
        help="An optional TSV file with prioritized ids for specific strains. " + \
             "The file is expected to have the columns `strain` and `id` " + \
             "and the `strain` column is expected to have unique strains. " + \
             "Any records with a strain that is included in this file " + \
             "will be dropped if the record id does not match the prioritized id. ")
    parser.add_argument("--output", required=True,
        help="Output of prioritized ids per strain.")

    args = parser.parse_args()

    hardcoded_prioritized_ids = {}
    if args.prioritized_ids:
        hardcoded_prioritized_ids = load_prioritized_ids(args.prioritized_ids)

    records = load_ndjson(stdin)
    ids_per_strain = track_ids_per_strain(
        records,
        args.strain_field,
        args.id_field,
        args.seq_field,
        hardcoded_prioritized_ids)

    prioritized_ids = pick_id_per_strain(ids_per_strain)
    with open(args.output, 'w') as f:
        for id in prioritized_ids:
            f.write(f"{id}\n")
