# Custom rules to run as part of the Nextstrain automated workflow
# The paths should be relative to the ingest directory.
custom_rules:
  - build-configs/nextstrain-automation/fetch_from_s3.smk
  - build-configs/nextstrain-automation/upload.smk

s3_dst: "s3://nextstrain-data-private/files/workflows/seasonal-flu"
s3_src: "s3://nextstrain-data-private/files/workflows/seasonal-flu"
