name: Upload data from fauna to S3

# Only support manual trigger of this workflow.
on:
  workflow_dispatch:
    inputs:
      triggerPublic:
        description: "Trigger Nextstrain public builds"
        required: true
        type: boolean
      publicDockerImage:
        description: "Specific container image to use for Nextstrain public builds"
        required: false
        type: string
      triggerPrivateNextflu:
        description: "Trigger private Nextflu builds"
        required: true
        type: boolean
      privateNextfluDockerImage:
        description: "Specific container image to use for private Nextflu builds"
        required: false
        type: string

jobs:
  upload:
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      runtime: docker
      run: |
        nextstrain build \
          --env AWS_ACCESS_KEY_ID \
          --env AWS_SECRET_ACCESS_KEY \
          --env RETHINK_AUTH_KEY \
          --env RETHINK_HOST \
          . \
          -j 2 \
          upload_all_titers \
          upload_all_raw_sequences \
          upload_all_sequences \
          upload_all_metadata \
          --configfile profiles/upload.yaml

  trigger-public-builds:
    needs: [upload]
    if: ${{ inputs.triggerPublic }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Nextstrain public builds
        run: |
          gh workflow run \
            run-public-builds.yaml \
            --repo nextstrain/seasonal-flu \
            -f dockerImage=${{ github.event.inputs.publicDockerImage }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  trigger-private-nextflu-builds:
    needs: [upload]
    if: ${{ inputs.triggerPrivateNextflu }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger private Nextflu builds
        run: |
          gh workflow run \
            run-private-nextflu-builds.yaml \
            --repo nextstrain/seasonal-flu \
            -f dockerImage=${{ github.event.inputs.privateNextfluDockerImage }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
